# ============================================================================
# 🐳 DOCKER COMPOSE - AMBIENTE COMPLETO BATE-PAPO
# ============================================================================
# 
# Microserviço bate-papo conectado ao infraestrutura-core:
# - MySQL 8.0 local com R2DBC
# - Redis do infraestrutura-core para cache e streams
# - Rede conexao-network-swarm
# 
# Uso: docker-compose up -d
# ============================================================================


services:
  # ========================================
  # 💬 MICROSERVIÇO BATE-PAPO
  # ========================================
  batepapo-service:
    image: ghcr.io/wibson82/conexao-de-sorte-backend-batepapo:latest
    restart: unless-stopped
    environment:
      # Database (infraestrutura centralizada)
      - conexao-de-sorte-database-r2dbc-url=${DATABASE_R2DBC_URL:-r2dbc:mysql://conexao-mysql:3306/conexao_chat}
      - conexao-de-sorte-database-username=${DATABASE_USERNAME:-conexao_user}
      - conexao-de-sorte-database-password=${DATABASE_PASSWORD:-conexao_pass}
      
      # Redis - Infraestrutura Core
      - conexao-de-sorte-redis-host=${REDIS_HOST:-conexao-redis}
      - conexao-de-sorte-redis-port=${REDIS_PORT:-6379}
      - conexao-de-sorte-redis-password=${REDIS_PASSWORD:-redis_pass}
      - conexao-de-sorte-redis-database=${REDIS_DATABASE:-5}  # Alterado de 2 para 5 para evitar conflito com gateway
      
      # JWT
      - conexao-de-sorte-jwt-jwks-uri=${CONEXAO_DE_SORTE_JWT_JWKS_URI:-http://autenticacao-service:8081/.well-known/jwks.json}
      - conexao-de-sorte-jwt-issuer=${CONEXAO_DE_SORTE_JWT_ISSUER:-https://auth.conexaodesorte.com}
      
      # CORS
      - conexao-de-sorte-cors-allowed-origins=${CONEXAO_DE_SORTE_CORS_ALLOWED_ORIGINS:-http://localhost:*,https://*.conexaodesorte.com}
      - conexao-de-sorte-cors-allow-credentials=${CONEXAO_DE_SORTE_CORS_ALLOW_CREDENTIALS:-true}

      # Server port
      - conexao-de-sorte-server-port=${CONEXAO_DE_SORTE_SERVER_PORT:-8090}
      
      # Features
      - FEATURE_BATEPAPO_MS=true
      - FEATURE_WEBSOCKET=true
      - FEATURE_SSE=true
      - FEATURE_MESSAGE_PERSISTENCE=true
      - FEATURE_REDIS_STREAMS=true
      - FEATURE_USER_PRESENCE=true
      - FEATURE_MESSAGE_HISTORY=true
      - FEATURE_ROOM_MANAGEMENT=true
      - FEATURE_AUDIT_LOGGING=true
      - FEATURE_METRICS=true
      
      # Chat Configuration
      - CHAT_MAX_MESSAGE_LENGTH=500
      - CHAT_MESSAGE_RETENTION_DAYS=30
      - CHAT_ONLINE_TIMEOUT_MINUTES=5
      - CHAT_HEARTBEAT_INTERVAL_SECONDS=30
      - CHAT_MAX_CONNECTIONS_PER_USER=3
      
      # Observability
      - TRACING_PROBABILITY=1.0
      - LOG_LEVEL=INFO
      
      # Performance
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      conexao-network-swarm:
        aliases:
          - conexao-batepapo
    volumes:
      - batepapo-logs:/app/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # ========================================
  # 🗄️ OBSERVAÇÃO: MySQL removido - usa infraestrutura centralizada
  # ========================================
  # MySQL agora fornecido pelo conexao-de-sorte-infraestrutura-core
  # Database: conexao_chat no servidor conexao-mysql

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
volumes:
  batepapo-logs:

# ========================================
# 🌐 REDE EXTERNA
# ========================================
networks:
  conexao-network-swarm:
    name: conexao-network-swarm
    external: true
