# ============================================================================
# 🐳 DOCKER COMPOSE - AMBIENTE COMPLETO BATE-PAPO
# ============================================================================
# 
# Orquestração completa do microserviço bate-papo:
# - MySQL 8.0 com R2DBC
# - Redis para cache e streams distribuídos
# - Prometheus para métricas
# - Grafana para dashboards
# - Volumes persistentes
# - Rede isolada
# 
# Uso: docker-compose up -d
# ============================================================================

version: '3.9'

services:
  # ========================================
  # 💬 MICROSERVIÇO BATE-PAPO
  # ========================================
  batepapo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batepapo-microservice
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      # Database
      - DB_HOST=batepapo-mysql
      - DB_PORT=3306
      - DB_NAME=conexao_sorte_batepapo
      - DB_USERNAME=batepapo_user
      - DB_PASSWORD=batepapo_pass123!
      
      # Redis
      - REDIS_HOST=batepapo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_pass123!
      
      # JWT
      - JWT_JWKS_URI=http://autenticacao-service:8081/.well-known/jwks.json
      - JWT_ISSUER=https://auth.conexaodesorte.com
      
      # Features
      - FEATURE_BATEPAPO_MS=true
      - FEATURE_WEBSOCKET=true
      - FEATURE_SSE=true
      - FEATURE_MESSAGE_PERSISTENCE=true
      - FEATURE_REDIS_STREAMS=true
      - FEATURE_USER_PRESENCE=true
      - FEATURE_MESSAGE_HISTORY=true
      - FEATURE_ROOM_MANAGEMENT=true
      - FEATURE_AUDIT_LOGGING=true
      - FEATURE_METRICS=true
      
      # Chat Configuration
      - CHAT_MAX_MESSAGE_LENGTH=500
      - CHAT_MESSAGE_RETENTION_DAYS=30
      - CHAT_ONLINE_TIMEOUT_MINUTES=5
      - CHAT_HEARTBEAT_INTERVAL_SECONDS=30
      - CHAT_MAX_CONNECTIONS_PER_USER=3
      
      # Observability
      - TRACING_PROBABILITY=1.0
      - LOG_LEVEL=INFO
      
      # Performance
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    depends_on:
      - batepapo-mysql
      - batepapo-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - batepapo-network
    volumes:
      - ./logs:/app/logs

  # ========================================
  # 🗄️ MYSQL DATABASE
  # ========================================
  batepapo-mysql:
    image: mysql:8.0
    container_name: batepapo-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"  # Porta diferente para evitar conflito
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass123!
      - MYSQL_DATABASE=conexao_sorte_batepapo
      - MYSQL_USER=batepapo_user
      - MYSQL_PASSWORD=batepapo_pass123!
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --max-connections=200
    volumes:
      - batepapo-mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/migrations:ro
    networks:
      - batepapo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ========================================
  # 🚀 REDIS CACHE & STREAMS
  # ========================================
  batepapo-redis:
    image: redis:7-alpine
    container_name: batepapo-redis
    restart: unless-stopped
    ports:
      - "6381:6379"  # Porta diferente para evitar conflito
    environment:
      - REDIS_PASSWORD=redis_pass123!
    command: >
      redis-server 
      --requirepass redis_pass123!
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 300
    volumes:
      - batepapo-redis-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - batepapo-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_pass123!", "ping"]
      timeout: 20s
      retries: 5

  # ========================================
  # 📈 PROMETHEUS (Métricas)
  # ========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: batepapo-prometheus
    restart: unless-stopped
    ports:
      - "9092:9090"  # Porta diferente para evitar conflito
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - batepapo-network
    depends_on:
      - batepapo-service

  # ========================================
  # 📊 GRAFANA (Dashboards)
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: batepapo-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"  # Porta diferente para evitar conflito
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - batepapo-network
    depends_on:
      - prometheus

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
volumes:
  batepapo-mysql-data:
    driver: local
  batepapo-redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# ========================================
# 🌐 REDE ISOLADA
# ========================================
networks:
  batepapo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16