# ============================================================================
# 🐳 DOCKER COMPOSE - AMBIENTE COMPLETO BATE-PAPO
# ============================================================================
# 
# Microserviço bate-papo conectado ao infraestrutura-core:
# - MySQL 8.0 local com R2DBC
# - Redis do infraestrutura-core para cache e streams
# - Rede conexao-network-swarm
# 
# Uso: docker-compose up -d
# ============================================================================


services:
  # ========================================
  # 💬 MICROSERVIÇO BATE-PAPO
  # ========================================
  batepapo-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: batepapo-microservice
    restart: unless-stopped
    ports:
      - "8079:8079"
    environment:
      # Database (infraestrutura centralizada)
      - conexao-de-sorte-database-r2dbc-url=r2dbc:mysql://conexao-mysql:3306/conexao_chat
      - conexao-de-sorte-database-username=${DATABASE_USERNAME}
      - conexao-de-sorte-database-password=${DATABASE_PASSWORD}
      
      # Redis - Infraestrutura Core
      - conexao-de-sorte-redis-host=conexao-redis
      - conexao-de-sorte-redis-port=6379
      - conexao-de-sorte-redis-password=${REDIS_PASSWORD}
      - conexao-de-sorte-redis-database=2
      
      # JWT
      - conexao-de-sorte-jwt-jwks-uri=http://autenticacao-service:8081/.well-known/jwks.json
      - conexao-de-sorte-jwt-issuer=https://auth.conexaodesorte.com
      
      # CORS
      - conexao-de-sorte-cors-allowed-origins=http://localhost:*,https://*.conexaodesorte.com
      - conexao-de-sorte-cors-allow-credentials=true
      
      # Features
      - FEATURE_BATEPAPO_MS=true
      - FEATURE_WEBSOCKET=true
      - FEATURE_SSE=true
      - FEATURE_MESSAGE_PERSISTENCE=true
      - FEATURE_REDIS_STREAMS=true
      - FEATURE_USER_PRESENCE=true
      - FEATURE_MESSAGE_HISTORY=true
      - FEATURE_ROOM_MANAGEMENT=true
      - FEATURE_AUDIT_LOGGING=true
      - FEATURE_METRICS=true
      
      # Chat Configuration
      - CHAT_MAX_MESSAGE_LENGTH=500
      - CHAT_MESSAGE_RETENTION_DAYS=30
      - CHAT_ONLINE_TIMEOUT_MINUTES=5
      - CHAT_HEARTBEAT_INTERVAL_SECONDS=30
      - CHAT_MAX_CONNECTIONS_PER_USER=3
      
      # Observability
      - TRACING_PROBABILITY=1.0
      - LOG_LEVEL=INFO
      
      # Performance
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8079/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - conexao-network
    volumes:
      - ./logs:/app/logs

  # ========================================
  # 🗄️ OBSERVAÇÃO: MySQL removido - usa infraestrutura centralizada
  # ========================================
  # MySQL agora fornecido pelo conexao-de-sorte-infraestrutura-core
  # Database: conexao_chat no servidor conexao-mysql

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
# Volumes do MySQL removidos - usa infraestrutura compartilhada
volumes:

# ========================================
# 🌐 REDE EXTERNA
# ========================================
networks:
  conexao-network:
    name: conexao-network-swarm
    external: true