# ============================================================================
# 🏗️ CONFIGURAÇÃO STAGING - MICROSERVIÇO BATE-PAPO
# ============================================================================
# Perfil otimizado para ambiente de staging com observabilidade enhanced
# Mantém padrões de produção com flexibilidade para testes
# ============================================================================

# ========================================
# 🌐 SERVIDOR
# ========================================
server:
  port: ${conexao-de-sorte-server-port:8083}
  shutdown: graceful
  servlet:
    context-path: /rest/v1

# ========================================
# 🗄️ BANCO DE DADOS - R2DBC
# ========================================
spring:
  application:
    name: batepapo-staging
    
  r2dbc:
    url: ${conexao-de-sorte-database-r2dbc-url:r2dbc:mysql://localhost:3307/conexao_sorte_chat}
    username: ${conexao-de-sorte-database-username:conexao_sorte}
    password: ${conexao-de-sorte-database-password}
    pool:
      enabled: true
      initial-size: 10  # Mais conexões para websockets
      max-size: 30
      max-idle-time: 30m
      
  # ========================================
  # 🗄️ FLYWAY PARA MIGRATIONS
  # ========================================
  flyway:
    enabled: true
    url: ${conexao-de-sorte-database-flyway-url:jdbc:mysql://localhost:3307/conexao_sorte_chat}
    user: ${conexao-de-sorte-database-username:conexao_sorte}
    password: ${conexao-de-sorte-database-password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # ========================================
  # 🚀 REDIS
  # ========================================
  data:
    redis:
      host: ${conexao-de-sorte-redis-host:localhost}
      port: ${conexao-de-sorte-redis-port:6380}
      password: ${conexao-de-sorte-redis-password}
      database: 4
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 16  # Mais conexões para pub/sub
          max-idle: 8
          min-idle: 2
          
  # ========================================
  # 🔐 SEGURANÇA JWT
  # ========================================
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${conexao-de-sorte-jwt-jwks-uri:http://localhost:8089/.well-known/jwks.json}
          issuer-uri: ${conexao-de-sorte-jwt-issuer:https://staging.conexaodesorte.com}

# ========================================
# 📊 ACTUATOR & OBSERVABILIDADE
# ========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,configprops
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    redis:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 30s
  metrics:
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      percentiles:
        '[http.server.requests]': 0.5,0.95,0.99
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% em staging para debug completo

# ========================================
# 📝 LOGGING ENHANCED
# ========================================
logging:
  level:
    root: INFO
    '[br.tec.facilitaservicos.batepapo]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.r2dbc]': INFO
    '[org.springframework.data.redis]': DEBUG
    '[reactor.netty.http.server]': INFO
    '[org.springframework.web.reactive]': DEBUG
    '[org.springframework.messaging]': DEBUG
    '[org.springframework.websocket]': DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [STAGING] %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - [STAGING] %msg%n"
  file:
    name: /tmp/batepapo-staging.log
    max-size: 100MB
    max-history: 30

debug: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha